name: ðŸ“Š GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    name: Gerar mÃ©tricas do perfil
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: ðŸ“Š Gerar mÃ©tricas
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: https-shini
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: push, issue, pr
          filename: metrics.svg
          output_action: commit
          committer_branch: output
          committer_message: "ðŸ“Š Atualizando mÃ©tricas do perfil"
