name: Generate Snake

on:
  schedule: # roda automaticamente em horários definidos
    - cron: "0 */12 * * *"  # a cada 12 horas
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gerar animação da cobrinha
        uses: Platane/snk@master
        with:
          github_user_name: https-shini
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e push do resultado
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Gerando animação da cobrinha"
          add: "dist/*.svg"
